### ISSUE TITLE
Sapper example not working on 1.0.1

### ISSUE THREAD

**Issue by klevente** [YogliB/svelte-fullcalendar#476]
Hi,

I am trying to get the new Sapper example project to work, however, upon starting the dev server, it crashes with the following message:

```
...\sapper\node_modules\@fullcalendar\daygrid\main.js:6
import './main.css';
       ^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (...\sapper\__sapper__\dev\server\server.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
> Server crashed
```

If I also include the interaction plugin, I get a different error:
```
...\sapper\node_modules\@fullcalendar\interaction\main.js:6
import { config, elementClosest, Emitter, applyStyle, whenTransitionDone, removeElement, ScrollController, ElementScrollController, computeInnerRect, WindowScrollController, preventSelection, preventContextMenu, allowSelection, allowContextMenu, ElementDragging, c
omputeRect, getClippingParents, pointInsideRect, isDateSpansEqual, constrainPoint, intersectRects, getRectCenter, diffPoints, mapHash, rangeContainsRange, interactionSettingsToStore, Interaction, enableCursor, disableCursor, triggerDateSelect, compareNumbers, getE
lSeg, getRelevantEvents, EventApi, createEmptyEventStore, applyMutationToEventStore, buildEventApis, interactionSettingsStore, startOfDay, diffDates, createDuration, identity, eventTupleToStore, isInteractionValid, parseDragMeta, elementMatches, refineEventDef, pa
rseEventDef, getDefaultEventEnd, createEventInstance, BASE_OPTION_DEFAULTS, createPlugin } from '@fullcalendar/common';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (...\sapper\__sapper__\dev\server\server.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
✔ service worker (25ms)
> Server crashed
```

Here is my `package.json` for reference:
```
{
	"dependencies": {
		"@fullcalendar/daygrid": "^5.3.2",
		"@fullcalendar/timegrid": "^5.3.1",
		"@fullcalendar/interaction": "^5.3.1",
		"compression": "^1.7.1",
		"polka": "next",
		"sirv": "^1.0.0"
	},
	"devDependencies": {
		"@babel/core": "^7.0.0",
		"@babel/plugin-syntax-dynamic-import": "^7.0.0",
		"@babel/plugin-transform-runtime": "^7.0.0",
		"@babel/preset-env": "^7.0.0",
		"@babel/runtime": "^7.0.0",
		"@rollup/plugin-babel": "^5.0.0",
		"@rollup/plugin-commonjs": "^14.0.0",
		"@rollup/plugin-node-resolve": "^8.0.0",
		"@rollup/plugin-replace": "^2.2.0",
		"npm-run-all": "^4.1.5",
		"rollup": "^2.3.4",
		"rollup-plugin-svelte": "^6.0.0",
		"rollup-plugin-terser": "^7.0.0",
		"sapper": "^0.28.0",
		"svelte": "^3.17.3",
		"svelte-fullcalendar": "^1.0.1"
	},
	"name": "@examples/sapper",
	"private": true,
	"scripts": {
		"build": "sapper build --legacy",
		"dev": "sapper dev",
		"export": "sapper export --legacy",
		"start": "node __sapper__/build"
	},
	"version": "1.0.0"
}
```

Thanks in advance for any help!

Edit: The vanilla Svelte example works without any issues out of the box.

**Comment by YogliB** [comment]
thanks! i'm looking into that.

**Comment by YogliB** [comment]
Docs are now updated about SSR, [take a look](https://github.com/YogliB/svelte-fullcalendar#ssr).
Sapper example is also updated and a new version is released, addressing SSR issues in the `Draggable` component.
